# Containerfile for building Eclipse Chariott runtime container
FROM registry.fedoraproject.org/fedora:38 as builder
ENV VERSION="56fac8c49eb19bc96dfab1ca10a6bd9a5a1985e4"
RUN dnf -y install rust cargo unzip cmake protobuf-devel
ADD https://github.com/eclipse-chariott/chariott/archive/${VERSION}.zip /tmp/chariott.zip
RUN unzip /tmp/chariott.zip -d /tmp;mv /tmp/chariott-${VERSION} /sdv
WORKDIR /sdv
RUN cargo build --release 

# Chariott Final Fedora Image
FROM registry.fedoraproject.org/fedora:38

# Copy our build
COPY --from=builder /sdv/target/release/chariott /usr/local/bin/chariott
COPY --from=builder /sdv/target/release/chariott.d /etc/

ENTRYPOINT ["chariott"]
