# Containerfile for building an grpcurl chariott proto toolbox
FROM registry.fedoraproject.org/fedora:38 as builder
ARG VERSION="e4b54b7ecec77933efad323351dfebe47fea7c2a"
RUN dnf -y install unzip
ADD https://github.com/eclipse-chariott/chariott/archive/${VERSION}.zip /tmp/chariott.zip
RUN unzip /tmp/chariott.zip -d /tmp;mv /tmp/chariott-${VERSION} /sdv
WORKDIR /sdv

# grpcurl chariott proto Final Fedora Image
FROM registry.fedoraproject.org/fedora:38
COPY --from=builder /sdv/proto /proto
RUN dnf -y install grpcurl; dnf clean all
COPY entrypoint.py /usr/local/bin/entrypoint.py
RUN chmod +x /usr/local/bin/entrypoint.py
ENTRYPOINT ["/usr/bin/python3", "-u", "/usr/local/bin/entrypoint.py"]
